export const FETCH_DATA = 'FETCH_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';

export const SET_RENDERING_FILTER = 'SET_RENDERING_FILTER';

// FILTER OPTIONS CONSTANTS
export const FilterOptions = {
	SHOW_ALL_ITEMS: 'SHOW_ALL_ITEMS',
	SHOW_COMPLETED_ITEMS: 'SHOW_COMPLETED_ITEMS',
	SHOW_ACTIVE_ITEMS: 'SHOW_ACTIVE_ITEMS'
};